=== troeschmichael/WebG/1. Block XML DTD/Aufgabe1+2/aufgabe1b.dtd
<!ELEMENT person (name, vorname, konto+)>
<!ELEMENT konto (kontonummer, guthaben)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT vorname (#PCDATA)>
<!ELEMENT kontonummer (#PCDATA)>
<!ELEMENT guthaben (#PCDATA)>
<!ATTLIST person pid ID #REQUIRED>
<!ATTLIST konto pid IDREF #REQUIRED>

=== troeschmichael/WebG/1. Block XML DTD/Aufgabe1+2/aufgabe1b.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE person SYSTEM "aufgabe1b.dtd" >

<person pid="p1">
    <name>Meier</name>
    <vorname>Hans</vorname>
    <konto pid="p1">
        <kontonummer>1234</kontonummer>
        <guthaben>1000</guthaben>
    </konto>
    <konto pid="p1">
        <kontonummer>4321</kontonummer>
        <guthaben>5000</guthaben>
    </konto>
</person>
