<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE emp:document [
        <!ELEMENT emp:document (emp:employee*)>
        <!ATTLIST emp:document
                xmlns:emp CDATA #FIXED "http://xmlpowercorp.com/dtds/">
        <!ELEMENT emp:employee (emp:name, emp:hiredate, emp:projects)>
        <!ELEMENT emp:name (emp:lastname, emp:firstname)>
        <!ELEMENT emp:lastname (#PCDATA)>
        <!ELEMENT emp:firstname (#PCDATA)>
        <!ELEMENT emp:hiredate (#PCDATA)>
        <!ELEMENT emp:projects (emp:project*)>
        <!ELEMENT emp:project (emp:product, emp:id, emp:price)>
        <!ELEMENT emp:product (#PCDATA)>
        <!ELEMENT emp:id (#PCDATA)>
        <!ELEMENT emp:price (#PCDATA)>
]>



<emp:document xmlns:emp="http://xmlpowercorp.com/dtds/">
    <emp:employee>
        <emp:name>
            <emp:lastname>MÃ¼ller</emp:lastname>
            <emp:firstname>Heiri</emp:firstname>
        </emp:name>
        <emp:hiredate>01.01.1980</emp:hiredate>
        <emp:projects>
            <emp:project>
                <emp:product>abc</emp:product>
                <emp:id>123</emp:id>
                <emp:price>20</emp:price>
            </emp:project>
        </emp:projects>
    </emp:employee>
    <emp:employee>
        <emp:name>
            <emp:lastname>Meier</emp:lastname>
            <emp:firstname>Hans</emp:firstname>
        </emp:name>
        <emp:hiredate>01.01.1990</emp:hiredate>
        <emp:projects>
            <emp:project>
                <emp:product>xyz</emp:product>
                <emp:id>124</emp:id>
                <emp:price>40</emp:price>
            </emp:project>
            <emp:project>
                <emp:product>lmn</emp:product>
                <emp:id>125</emp:id>
                <emp:price>50</emp:price>
            </emp:project>
        </emp:projects>
    </emp:employee>
</emp:document>